### ISSUE TITLE
it is still not working with gosh

### ISSUE THREAD

**Issue by kotarusv** [abdfnx/gosh#2]
go get github.com/abdfnx/gosh
go get: github.com/abdfnx/gosh@v0.3.15: parsing go.mod:
        module declares its path as: github.com/abdfnx/shell
                but was required as: github.com/abdfnx/gosh

goshell go version                   
go version go1.17.3 darwin/amd64

**Comment by kotarusv** [comment]
BTY if it works, this is very useful package. I am always looking for simple way to execute shell commands in Golang similar to `` Perl or Ruby

**Comment by abdfnx** [comment]
run `go get -v github.com/abdfnx/gosh@v0.3.5`

**Comment by kotarusv** [comment]
It is working. Thanks. Can you suggest this module is ready for production? Perl, Ruby support executing shell commands directly from code using `` syntax. I knew this is not a good idea by executing shell commands directly from code due to security and shell escape reasons.  Go support os/exec package but that is ok for simple OS commands but won't execute shell command as it is due to pipes, single and double quotes in the complex shell command. 

This module seems to be an answer for quickly executing shell commands similar to Perl or Ruby but would like t to hear from you before using in production and critical environments.

**Comment by abdfnx** [comment]
hi @kotarusv , yes you can run commands with `` syntax, look at this example:

```go
gosh.ShellCommand(`
  mood="👨‍💻"

  if [ $mood != "😪" ]; then
    echo "still coding"
  fi
`)
```

**Comment by abdfnx** [comment]
is everything okay @kotarusv
